apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage1-claim
  namespace: string-output-namespace
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi