apiVersion: v1
kind: Service
metadata:
  name: fil7er-output-generator-svc
spec:
  type: LoadBalancer
  selector:
    app: fil7er-output-generator
  ports:
    - name: http
      protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30000