apiVersion: v1
kind: Service
metadata:
  name: fil7er-output-generator-svc
spec:
  type: ClusterIP
  selector:
    app: fil7er-output-generator
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: read-file-port
  externalIPs:
    - "1.2.4.120"